name: po_editor_translations
description: Simple CLI for getting translations from POEditor.
version: 0.1.0
homepage: https://github.com/Flarrow-Company/po-editor-translations

environment:
  sdk: ^3.1.5

dependencies:

  http: ^1.1.0
  args: ^2.4.2

dev_dependencies:
  lints: ^3.0.0
